---
title: "index"
output: html_document
---

```{r}
library(DBI)
library(RSQLite)
```


```{r}
drv = dbDriver("SQLite")

retail_sales_db = dbConnect(drv, dbname = "./data/retail_sales_data.sqlite")
dbExecute(retail_sales_db, "PRAGMA foreign_keys = ON")
```

```{r}
customers = read.csv("./data/customers.csv",
                     header = TRUE, stringsAsFactors = FALSE)
colnames(customers) = c("customer_id", "name", "email", "phone_number", "city", "country", "gender", "date_of_birth", "job_title")
```

```{r}
discounts = read.csv("./data/discounts.csv",
                     header = TRUE, stringsAsFactors = FALSE)
colnames(discounts) = c("start_date", "end_date", "discount", "description", "category", "sub_category")
```

```{r}

employees = read.csv("./data/employees.csv",
                     header = TRUE, stringsAsFactors = FALSE)
colnames(employees) = c("employee_id", "store_id", "name", "position")
```

```{r}
products = read.csv("./data/products.csv",
                     header = TRUE, stringsAsFactors = FALSE)[,c(1,2,3,8,10,11,12)]
colnames(products) = c("product_id", "category", "sub_category", "description", "color", "sizes", "production_cost")
```

```{r}
stores = read.csv("./data/stores.csv",
                     header = TRUE, stringsAsFactors = FALSE)
colnames(stores) = c("store_id", "country", "city", "store_name", "num_of_employees", "zip_code", "latitude", "longitude")
```

```{r}
transactions = read.csv("./data/transactions.csv",
                     header = TRUE, stringsAsFactors = FALSE)
colnames(transactions) = c("invoice_id", "line", "customer_id", "product_id", "size", "color", "unit_price", "quantity", "date", "discount", "line_total", "store_id", "employee_id", "currency", "currency_symbol", "sku", "transaction_type", "payment_method", "invoice_total")
```


**TABLE FOR CUSTOMERS**
```{r}

dbExecute(retail_sales_db, "
          CREATE TABLE CUSTOMERS (
          customer_id INTEGER PRIMARY KEY,
          name TEXT,
          email TEXT,
          phone_number TEXT,
          city TEXT,
          country TEXT,
          gender CHAR(1),
          date_of_birth TEXT,
          job_title TEXT
          )")

dbWriteTable(retail_sales_db, 
             "CUSTOMERS", customers, append = TRUE)

```


**TABLE FOR STORES**
```{r}
dbExecute(retail_sales_db, "
          CREATE TABLE STORES (
          store_id INTEGER PRIMARY KEY,
          country TEXT,
          city TEXT,
          store_name TEXT,
          num_of_employees INTEGER,
          zip_code CHAR(10),
          latitude FLOAT,
          longitude FLOAT
          )")

dbWriteTable(retail_sales_db, 
             "STORES", stores, append = TRUE)

```


**TABLE FOR EMPLOYEES**
```{r}
dbExecute(retail_sales_db, "
          CREATE TABLE EMPLOYEES (
          employee_id INTEGER PRIMARY KEY,
          store_id INTEGER,
          name TEXT,
          position TEXT,
          FOREIGN KEY (store_id) REFERENCES STORES (store_id)
          )")

dbWriteTable(retail_sales_db, 
             "EMPLOYEES", employees, append = TRUE)


```


**TABLE FOR PRODUCTS**
```{r}
dbExecute(retail_sales_db, "
          CREATE TABLE PRODUCTS (
          product_id INTEGER PRIMARY KEY,
          category TEXT,
          sub_category TEXT,
          description TEXT,
          color TEXT,
          sizes CHAR(20),
          production_cost FLOAT
          )")


dbWriteTable(retail_sales_db, 
             "PRODUCTS", products, append = TRUE)


```

```{r}
transactions


```

**TABLE FOR TRANSACTIONS**
```{r}
dbExecute(retail_sales_db, "
          CREATE TABLE TRANSACTIONS (
          invoice_id CHAR(20),
          line INTEGER,
          customer_id INTEGER,
          product_id INTEGER,
          size CHAR(5),
          color TEXT,
          unit_price FLOAT,
          quantity INTEGER,
          date CHAR(20),
          discount FLOAT,
          line_total FLOAT,
          store_id INTEGER,
          employee_id INTEGER,
          currency TEXT,
          currency_symbol CHAR(5),
          sku CHAR(20),
          transaction_type TEXT,
          payment_method TEXT,
          invoice_total FLOAT,
          FOREIGN KEY (customer_id) REFERENCES CUSTOMERS (customer_id),
          FOREIGN KEY (product_id) REFERENCES PRODUCTS (product_id),
          FOREIGN KEY (store_id) REFERENCES STORES (store_id),
          FOREIGN KEY (employee_id) REFERENCES EMPLOYEES (employee_id)
          )")

```

```{r}
dbWriteTable(retail_sales_db, 
             "TRANSACTIONS", transactions, append = TRUE)


```









```{r}
dbGetQuery(retail_sales_db, "
           SELECT * 
           FROM PRODUCTS
           LIMIT 10")
# dbListTables(retail_sales_db)
# dbListFields(retail_sales_db, "EMPLOYEES")
# dbExecute(retail_sales_db, "PRAGMA foreign_key_list(EMPLOYEES)")
# 
# 
# dbGetQuery(retail_sales_db, "
#            SELECT employee_id, name, position, STORES.store_name
#            FROM EMPLOYEES INNER JOIN STORES
#            ON EMPLOYEES.store_id = STORES.store_id
#            LIMIT 10")
```





